### ISSUE TITLE
El informe del tp2 no compila

### ISSUE THREAD

**Issue by Martinamonastra20** [luzalbaposse/Inferencia-Estadistica#1]
El error es:
> rmarkdown::render()
Error in rmarkdown::render() : 
  argument "input" is missing, with no default
> rmarkdown::render(tp.Rmd,pdf_document, tp)
Error: object 'pdf_document' not found
> rmarkdown::render(tp.Rmd,pdf_document(), tp)
Error in pdf_document() : could not find function "pdf_document"
> rmarkdown::render(tp.Rmd,pdf_documents(), tp)
Error in pdf_documents() : could not find function "pdf_documents"
> rmarkdown::render("informe.rmd", output_format = "pdf_document")
Error in abs_path(input) : The file 'informe.rmd' does not exist.
In addition: Warning message:
In normalizePath(x, winslash = winslash, mustWork = must_work) :
  path[1]="informe.rmd": No such file or directory
> rmarkdown::render("tp.rmd", output_format = "pdf_document")

processing file: tp.rmd
  |......................................................................................| 100% [unnamed-chunk-10]Error in `plot.new()`:
! figure margins too large
Backtrace:
 1. graphics::hist(...)
 2. graphics::hist.default(...)
 4. graphics:::plot.histogram(...)
 5. graphics::plot.new()

Quitting from lines 172-191 [unnamed-chunk-10] (tp.rmd)
                                                                                                                                                
> rmarkdown::render("tp.rmd", output_format = "pdf_document")

processing file: tp.rmd
  |..................................................................................    |  95% [unnamed-chunk-10]Error in `plot.new()`:
! figure margins too large
Backtrace:
 1. graphics::hist(...)
 2. graphics::hist.default(...)
 4. graphics:::plot.histogram(...)
 5. graphics::plot.new()

Quitting from lines 171-190 [unnamed-chunk-10] (tp.rmd)

**Comment by unfoquito** [comment]
Ready
